version: '2'
services:
 application-server:
  build: ./application-server
  ports:
   - "80:80"
  restart: always
  #simplify development by allowing instantaneous code changes. Unsafe. Remove for deployment
  volumes:
  - ./application-server/src:/var/www
  depends_on:
   - database-server
 database-server:
  ports:
   - "3306:3306"
  restart: always
  build: ./database-server
  volumes: 
   - packapps-db:/var/lib/mysql
 #phpmyadmin for database visualization. remove for deployment
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_HOST=database-server
  restart: always
  ports:
   - 8080:80
  volumes:
   - /sessions
volumes:
 packapps-db:
