<?php
/**
 * Created by PhpStorm.
 * User: MAC
 * Date: 7/20/2015
 * Time: 11:21 AM
 */
//This file parses an XLS file generated by the fruit test suite FTA and returns its data as json
//only supports 5, 10, or 15 samples in a file
include_once("../Classes/excel_reader2.php");
$xlsdata = new Spreadsheet_Excel_Reader($_FILES['0']['tmp_name'],false);

if($xlsdata->rowcount() == 23) {
    //5 samples
    //creates array of weight, press1, press2
    echo json_encode(array_merge(array("NumSamples"=>"5","BlockID"=>$xlsdata->val('18', 'B')),
    array(
    array($xlsdata->val('2', 'C'),$xlsdata->val('2', 'B'),$xlsdata->val('3', 'B')),
    array($xlsdata->val('4', 'C'),$xlsdata->val('4', 'B'),$xlsdata->val('5', 'B')),
    array($xlsdata->val('6', 'C'),$xlsdata->val('6', 'B'),$xlsdata->val('7', 'B')),
    array($xlsdata->val('8', 'C'),$xlsdata->val('8', 'B'),$xlsdata->val('9', 'B')),
    array($xlsdata->val('10', 'C'),$xlsdata->val('10', 'B'),$xlsdata->val('11', 'B')))));
}

elseif($xlsdata->rowcount() == 33)
{
    //10 samples
    echo json_encode(array_merge(array("NumSamples"=>"10","BlockID"=>$xlsdata->val('28', 'B')),
    array(
        array($xlsdata->val('2', 'C'),$xlsdata->val('2', 'B'),$xlsdata->val('3', 'B')),
        array($xlsdata->val('4', 'C'),$xlsdata->val('4', 'B'),$xlsdata->val('5', 'B')),
        array($xlsdata->val('6', 'C'),$xlsdata->val('6', 'B'),$xlsdata->val('7', 'B')),
        array($xlsdata->val('8', 'C'),$xlsdata->val('8', 'B'),$xlsdata->val('9', 'B')),
        array($xlsdata->val('10', 'C'),$xlsdata->val('10', 'B'),$xlsdata->val('11', 'B')),
        array($xlsdata->val('12', 'C'),$xlsdata->val('12', 'B'),$xlsdata->val('13', 'B')),
        array($xlsdata->val('14', 'C'),$xlsdata->val('14', 'B'),$xlsdata->val('15', 'B')),
        array($xlsdata->val('16', 'C'),$xlsdata->val('16', 'B'),$xlsdata->val('17', 'B')),
        array($xlsdata->val('18', 'C'),$xlsdata->val('18', 'B'),$xlsdata->val('19', 'B')),
        array($xlsdata->val('20', 'C'),$xlsdata->val('20', 'B'),$xlsdata->val('21', 'B')))));
}
elseif($xlsdata->rowcount() == 43) {
    //15 samples
    echo json_encode(array_merge(array("NumSamples"=>"15","BlockID"=>$xlsdata->val('38', 'B')),
        array(
            array($xlsdata->val('2', 'C'),$xlsdata->val('2', 'B'),$xlsdata->val('3', 'B')),
            array($xlsdata->val('4', 'C'),$xlsdata->val('4', 'B'),$xlsdata->val('5', 'B')),
            array($xlsdata->val('6', 'C'),$xlsdata->val('6', 'B'),$xlsdata->val('7', 'B')),
            array($xlsdata->val('8', 'C'),$xlsdata->val('8', 'B'),$xlsdata->val('9', 'B')),
            array($xlsdata->val('10', 'C'),$xlsdata->val('10', 'B'),$xlsdata->val('11', 'B')),
            array($xlsdata->val('12', 'C'),$xlsdata->val('12', 'B'),$xlsdata->val('13', 'B')),
            array($xlsdata->val('14', 'C'),$xlsdata->val('14', 'B'),$xlsdata->val('15', 'B')),
            array($xlsdata->val('16', 'C'),$xlsdata->val('16', 'B'),$xlsdata->val('17', 'B')),
            array($xlsdata->val('18', 'C'),$xlsdata->val('18', 'B'),$xlsdata->val('19', 'B')),
            array($xlsdata->val('20', 'C'),$xlsdata->val('20', 'B'),$xlsdata->val('21', 'B')),
            array($xlsdata->val('22', 'C'),$xlsdata->val('22', 'B'),$xlsdata->val('23', 'B')),
            array($xlsdata->val('24', 'C'),$xlsdata->val('24', 'B'),$xlsdata->val('25', 'B')),
            array($xlsdata->val('26', 'C'),$xlsdata->val('26', 'B'),$xlsdata->val('27', 'B')),
            array($xlsdata->val('28', 'C'),$xlsdata->val('28', 'B'),$xlsdata->val('29', 'B')),
            array($xlsdata->val('30', 'C'),$xlsdata->val('30', 'B'),$xlsdata->val('31', 'B')))));
}
else{die(header("HTTP/1.1 500 Internal Server Error"));}